In [1]:
import torch
torch.__version__

'2.1.0.dev20230418'

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5335, 0.8181, 0.0974],
        [0.7531, 0.8504, 0.0981],
        [0.8505, 0.3563, 0.1402],
        [0.9667, 0.6899, 0.2980],
        [0.5199, 0.8657, 0.2430]])


In [10]:
#creating a SCALAR = a single number and it's a zero dimension tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
#check the dimensions of a tensor
scalar.ndim

0

In [16]:
#create a tensor object with 2 elements in 1 dimension
vector = torch.tensor([7, 7])
print("The dimension of vector is " + str(vector.ndim))
print("The number of elements inside the vector is " + str(vector.shape))

The dimension of vector is 1
The number of elements inside the vector is torch.Size([2])


* matrix is a multiple vectors combined.

* number of dimensions in a matrix = number of "[" on one side of the matrix

In [22]:
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX.ndim
print("The shape of the matrix is: "+str(matrix.shape))

The shape of the matrix is: torch.Size([2, 2])


* Note that MATRIX, TENSOR is usually denoted with capitals; scalar, vector with regular

### scalar < vector < matrix < tensor

In [23]:
#use rand function to create a random tensor
RANDOM_TENSOR = torch.rand(size = (4, 5))
RANDOM_TENSOR, RANDOM_TENSOR.dtype

(tensor([[0.7980, 0.8786, 0.8854, 0.6030, 0.8769],
         [0.7908, 0.7495, 0.5271, 0.2237, 0.9415],
         [0.9012, 0.3845, 0.5082, 0.4489, 0.0028],
         [0.9917, 0.5022, 0.8552, 0.4559, 0.6612]]),
 torch.float32)

In [24]:
#use rand to create a tensor with shape of [200, 200, 4]
RANDOM_IMAGE_SIZE_TENSOR = torch.rand(size = (200, 200, 4))
print("The shape of the tensor is "+str(RANDOM_IMAGE_SIZE_TENSOR.shape))
print("The number of dimensions is "+str(RANDOM_IMAGE_SIZE_TENSOR.ndim))

The shape of the tensor is torch.Size([200, 200, 4])
The number of dimensions is 3


### Create a random tensor with 0 and 1

In [26]:
zeros = torch.zeros(size=(3, 4, 4))
print(zeros)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [27]:
ones = torch.ones(size=(3, 4, 4))
print(ones)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


### Create a range and tensors like

In [29]:
zero_to_nine = torch.arange(start=0, end=9, step=1)
print(zero_to_nine)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


* Create a tensor of a certain type with the same shape as another tensor

In [30]:
nine_ones = torch.ones_like(input=zero_to_nine)
print(nine_ones)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])
